<a href="https://colab.research.google.com/github/dudu-ibm/learn-ibm/blob/main/machine_learning_wineproject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#pip install tensorflow==1.2.0 --ignore-installed
# Requires the latest pip
#pip install --upgrade pip

# Current stable release for CPU and GPU
#pip install tensorflow

# Or try the preview build (unstable)
#pip install tf-nightly

In [1]:
import pandas as pd
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers

In [2]:
df = pd.read_csv('/content/wine_dataset.csv')

In [3]:
df

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,red
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6,white
6493,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5,white
6494,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6,white
6495,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7,white
6496,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6,white

In [4]:
df.describe()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
count,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000
mean,7.215307,0.339666,0.318633,5.443235,0.056034,30.525319,115.744574,0.994697,3.218501,0.531268,10.491801,5.818378
std,1.296434,0.164636,0.145318,4.757804,0.035034,17.749400,56.521855,0.002999,0.160787,0.148806,1.192712,0.873255
min,3.800000,0.080000,0.000000,0.600000,0.009000,1.000000,6.000000,0.987110,2.720000,0.220000,8.000000,3.000000
25%,6.400000,0.230000,0.250000,1.800000,0.038000,17.000000,77.000000,0.992340,3.110000,0.430000,9.500000,5.000000
50%,7.000000,0.290000,0.310000,3.000000,0.047000,29.000000,118.000000,0.994890,3.210000,0.510000,10.300000,6.000000
75%,7.700000,0.400000,0.390000,8.100000,0.065000,41.000000,156.000000,0.996990,3.320000,0.600000,11.300000,6.000000
max,15.900000,1.580000,1.660000,65.800000,0.611000,289.000000,440.000000,1.038980,4.010000,2.000000,14.900000,9.000000

In [5]:
df.dtypes

fixed_acidity           float64
volatile_acidity        float64
citric_acid             float64
residual_sugar          float64
chlorides               float64
free_sulfur_dioxide     float64
total_sulfur_dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
style                    object
dtype: object

In [6]:
df['style'] = df['style'].replace('red', 0)

In [7]:
df['style'] = df['style'].replace('white', 1)

In [8]:
#separando as variáveis em preditoras e variável alvo

y = df['style']
x = df.drop('style', axis = 1)

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
#criando conjunto de dados de treino e teste
x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size = 0.3)

In [11]:
x_treino.shape
#y_treino.shape

(4547, 12)

In [12]:
from sklearn.ensemble import ExtraTreesClassifier

In [13]:
#criação do modelo

modelo = ExtraTreesClassifier()
modelo.fit(x_treino, y_treino)

#imprimindo resultados

resultado = modelo.score(x_teste, y_teste)
print('Acurácia:', resultado)

Acurácia: 0.9974358974358974

In [14]:
y_teste[400:415]

883     0
4786    1
4721    1
2454    1
1081    0
23      0
5228    1
4766    1
2178    1
2854    1
2288    1
4693    1
2397    1
4218    1
3642    1
Name: style, dtype: int64

In [15]:
x_teste[400:415]

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
883,7.2,0.60,0.04,2.5,0.076,18.0,88.0,0.99745,3.53,0.55,9.5,5
4786,6.7,0.18,0.37,1.3,0.027,42.0,125.0,0.98939,3.24,0.37,12.8,7
4721,5.6,0.18,0.27,1.7,0.030,31.0,103.0,0.98892,3.35,0.37,12.9,6
2454,7.4,0.20,0.35,2.1,0.038,30.0,116.0,0.99490,3.49,0.77,10.3,7
1081,7.9,0.30,0.68,8.3,0.050,37.5,289.0,0.99316,3.01,0.51,12.3,7
23,8.5,0.49,0.11,2.3,0.084,9.0,67.0,0.99680,3.17,0.53,9.4,5
5228,6.4,0.36,0.20,5.7,0.118,61.0,172.0,0.99460,3.24,0.43,9.5,6
4766,5.6,0.28,0.40,6.1,0.034,36.0,118.0,0.99144,3.21,0.43,12.1,7
2178,6.0,0.38,0.26,6.0,0.034,42.0,134.0,0.99120,3.38,0.38,12.3,7
2854,6.4,0.22,0.34,1.8,0.057,29.0,104.0,0.99590,3.81,0.57,10.3,6
2288,6.7,0.17,0.37,2.0,0.039,34.0,125.0,0.99220,3.26,0.60,10.8,7
4693,9.7,0.24,0.49,4.9,0.032,3.0,18.0,0.99368,2.85,0.54,10.0,6
2397,5.4,0.18,0.24,4.8,0.041,30.0,113.0,0.99445,3.42,0.40,9.4,6
4218,6.6,0.35,0.35,6.0,0.063,31.0,150.0,0.99537,3.10,0.47,9.4,6
3642,7.4,0.18,0.34,2.7,0.030,30.0,107.0,0.99200,2.97,0.53,11.0,6

In [16]:
previsoes = modelo.predict(x_teste[400:415])

In [17]:
previsoes

array([0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1])